# clean up:
# rm -rf ~/.bundle/ ~/.gem/; rm -rf $GEM_HOME/bundler/ $GEM_HOME/cache/bundler/; rm -rf .bundle/; rm -rf vendor/cache/; rm -rf Gemfile.lock

source 'https://rubygems.org'

gem 'yajl-ruby'
gem 'uuidtools'
gem 'faraday'
gem 'uber-s3'
gem 'addressable'

gem 'iron_worker_ng'
gem 'actionmailer'
gem 'rails_config'
